#!/usr/bin/perl
    use strict;
    use Daemon::Control;

    exit Daemon::Control->new(
        name        => "# Octopus IRC Service",
        lsb_start   => '$syslog $remote_fs',
        lsb_stop    => '$syslog',
        lsb_sdesc   => 'Octopus IRC Service',
        lsb_desc    => 'Octopus IRC Service',
        path        => '/home/remylaunay/Devel/octopus',

        program     => '/home/remylaunay/Devel/octopus/octopus.pl',

        pid_file    => '/home/remylaunay/Devel/octopus/octopus.pid',
        stderr_file => '/home/remylaunay/Devel/octopus/octopus.log',
        stdout_file => '/home/remylaunay/Devel/octopus/octopus.log',

        fork        => 2,

    )->run;
